import { defineTool } from "eve/tools";
import { z } from "zod";

// Builds the report Markdown the on-prem watcher expects (matches
// modes/oferta.md's Block A-G shape + a first-class `## Machine Summary`
// YAML block). Deterministic formatting only -- no model call here, the
// grader subagent already did the reasoning; this just assembles its
// structured output into the report on-prem parses.
//
// Coverage note: Blocks E (Customization Plan) and F (Interview Plan) are
// intentionally thin here. Those are interactive, cover-letter/interview-prep
// flows on-prem (modes/cover.md, interview-prep) that need a human's angle --
// the cloud side's job is triage-grading, not the full evaluation.

const dimensionNarrativesSchema = z.object({
  matchWithCv: z.string(),
  northStarAlignment: z.string(),
  comp: z.string(),
  culturalSignals: z.string(),
  redFlags: z.string(),
});

export default defineTool({
  description: "Format a graded posting into the report Markdown + Machine Summary YAML the on-prem watcher expects.",
  inputSchema: z.object({
    company: z.string(),
    role: z.string(),
    url: z.string(),
    date: z.string(),
    score: z.number(),
    archetype: z.string(),
    legitimacyTier: z.enum(["High Confidence", "Proceed with Caution", "Suspicious"]),
    hardStops: z.array(z.string()),
    softGaps: z.array(z.string()),
    topStrengths: z.array(z.string()),
    riskLevel: z.enum(["Low", "Medium", "High"]),
    confidence: z.enum(["Low", "Medium", "High"]),
    nextAction: z.string(),
    dimensionNarratives: dimensionNarrativesSchema,
  }),
  execute(input) {
    const list = (items: string[], empty: string) => (items.length ? items.map((i) => `- ${i}`).join("\n") : empty);
    // Ephemeral cloud-side tracking id, distinct from the on-prem sequential
    // report number -- reserve-report-num.mjs assigns the real number when
    // the watcher writes this content to reports/. This id just needs to be
    // stable enough to tag the Slack post and thread.
    const jobId = `${input.company.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${Date.now()}`;

    const machineSummary = [
      "```yaml",
      `company: "${input.company}"`,
      `role: "${input.role}"`,
      `score: ${input.score.toFixed(1)}`,
      `legitimacy_tier: "${input.legitimacyTier}"`,
      `archetype: "${input.archetype}"`,
      `final_decision: "${input.score >= 3.7 ? "Apply" : input.score >= 2.1 ? "Consider" : "Skip"}"`,
      `hard_stops:${input.hardStops.length ? "\n" + input.hardStops.map((h) => `  - "${h}"`).join("\n") : " []"}`,
      `soft_gaps:${input.softGaps.length ? "\n" + input.softGaps.map((g) => `  - "${g}"`).join("\n") : " []"}`,
      `top_strengths:${input.topStrengths.length ? "\n" + input.topStrengths.map((s) => `  - "${s}"`).join("\n") : " []"}`,
      `risk_level: "${input.riskLevel}"`,
      `confidence: "${input.confidence}"`,
      `next_action: "${input.nextAction}"`,
      "```",
    ].join("\n");

    // The report header block. Doubles as the compact Slack message (`slackText`):
    // it's all the human reader needs in #job-pipeline — the full Block A-G detail
    // rides along as the attached report file and lands in the on-prem report.
    const header = `# Evaluation: ${input.company} — ${input.role}

**Date:** ${input.date}
**Score:** ${input.score.toFixed(1)}/5
**Legitimacy:** ${input.legitimacyTier}
**URL:** ${input.url}
**PDF:** ❌
**Source:** cloud (daily scan)`;

    const markdown = `${header}

---

## A) Role Summary

${input.company} — ${input.role}. Archetype: ${input.archetype}.

## B) Match with CV

${input.dimensionNarratives.matchWithCv}

**Top strengths:**
${list(input.topStrengths, "None identified.")}

## C) Level and Strategy

${input.dimensionNarratives.northStarAlignment}

## D) Comp and Demand

${input.dimensionNarratives.comp}

## E) Customization Plan

Not generated by the cloud grader. Run \`/career-ops cover {report-number}\` on-prem (once filed) for a tailored cover-letter angle.

## F) Interview Plan

Not generated by the cloud grader. Run \`/career-ops interview-prep\` on-prem once you decide to move forward.

## G) Posting Legitimacy

**Tier:** ${input.legitimacyTier}

${input.dimensionNarratives.redFlags}

**Hard stops:**
${list(input.hardStops, "None detected.")}

**Soft gaps:**
${list(input.softGaps, "None detected.")}

---

## Machine Summary

${machineSummary}
`;

    return { markdown, slackText: header, jobId };
  },
});
